vim.opt.clipboard = "unnamedplus"   -- enable system clipboard
vim.opt.syntax = "on"               -- syntax highlighting
vim.opt.number = true               -- line number
vim.opt.ignorecase = true           -- ignore case when completing file names
vim.opt.smartcase = true            -- no ignore case when pattern has uppercase
vim.opt.wrap = true                 -- wrap text
vim.opt.undofile = true             -- save undo information in a file
vim.opt.tabstop = 2                 -- spaces per tab
vim.opt.softtabstop = 2             -- spaces per tab 
vim.opt.shiftwidth = 2              -- spaces per indent
vim.opt.numberwidth = 2             -- width of number column
vim.opt.mouse = "a"                 -- enable mouse 
