vim.o.clipboard = "unnamedplus"   -- enable system clipboard
vim.o.syntax = "on"               -- syntax highlighting
vim.o.number = true               -- line number
vim.o.ignorecase = true           -- ignore case when completing file names
vim.o.smartcase = true            -- no ignore case when pattern has uppercase
vim.o.wrap = true                 -- wrap text
vim.o.undofile = true             -- save undo information in a file
vim.o.tabstop = 2                 -- spaces per tab
vim.o.softtabstop = 2             -- spaces per tab 
vim.o.shiftwidth = 2              -- spaces per indent
vim.o.numberwidth = 2             -- width of number column
vim.o.mouse = "a"                 -- enable mouse 
